---
# namespace
apiVersion: v1
kind: Namespace
metadata:
  name: aspnet-app
  labels:
    name: aspnet-app
---
#service account
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 2217d74b-e1ab-410b-8ba3-9406e4af0d90
    azure.workload.identity/tenant-id: d5080e1b-64bc-40e7-9565-31d084679242
  labels:
    azure.workload.identity/use: "true"  
  name: aspnet-sa
  namespace: aspnet-app

---
#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-app-deployment
  namespace: aspnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      service: aspnet-app
  template:
    metadata:
      labels:
        app: aspnet-app
        service: aspnet-app
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: aspnet-sa
      containers:
      - name: aspnet-app
        image: rbrcr.azurecr.io/aspnetapp:58
        imagePullPolicy: IfNotPresent
        resources:
            requests:
                cpu: 500m
                memory: 256Mi
            limits:
                cpu: 750m
                memory: 512Mi
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        - name: "ASPNETCORE_URLS"
          value: "http://+:8080"
        
        
          
---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aspnet-app
  name: aspnet-app-service
  namespace: aspnet-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: aspnet-app
  type: ClusterIP

---
#ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aspnet-app-ingress
  namespace: aspnet-app
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - wid.azureholic.com
    secretName: tls-secret
  rules:
  - host: wid.azureholic.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aspnet-app-service
            port:
              number: 80