name: Build and Deploy to AKS
on: workflow_dispatch

permissions:
      id-token: write
      contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
  
    - name: Azure Login (Federated)
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Build Container
      working-directory: ./WorkloadIdentity.Web
      run: az acr build -r rbrcontainerregistry -t rbrcontainerregistry.azurecr.io/aspnetapp:latest --file dockerfile --platform linux .

    - name: Get AKS Credentials
      run: az aks get-credentials -g rg-k8s --name rbr-aks
      
    - name: Deploy to AKS
      working-directory: ./BuildAndDeploy
      run: kubectl apply -f kubedeploy.yaml
      
