name: Build and Deploy to AKS
on: 
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/**'

permissions:
  id-token: write
  contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
  
    - name: Azure Login (Federated)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Build Container
      working-directory: ./WorkloadIdentity.Web
      run: az acr build -r rbrcontainerregistry -t rbrcontainerregistry.azurecr.io/aspnetapp:${{ github.run_number }} --file dockerfile --platform linux .

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: 'rg-k8s' 
        cluster-name: 'rbr-aks'
  
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      
    - name: Deploy to AKS
      uses: Azure/k8s-deploy@v4
      with:
        namespace: 'default'
        manifests: ./BuildAndDeploy/kubedeploy.yaml
        images: 'rbrcontainerregistry.azurecr.io/aspnetapp:${{ github.run_number }}'
        pull-images: false 
      
