name: Build Container
on: 
  workflow_dispatch:
 

permissions:
  id-token: write
  contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
  
    - name: Azure Login (Federated)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
   
    - name: Build Container
      working-directory: ./WorkloadIdentity.Web
      run: az acr build -r rbrcr -t rbrcr.azurecr.io/aspnetapp:${{ github.run_number }} --file dockerfile --platform linux .

  
